import React from 'react';
import type { Metadata } from 'next';
import '@/app/styles/reset.css';
import '@/app/styles/fonts.css';
import '@/app/styles/globals.css';
import Header from '@/app/components/header';
import Loader from '@/app/components/loader';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Header />
        <Loader />
        <main>{children}</main>
      </body>
    </html>
  )
}
