import React from 'react';
import type { Metadata } from 'next';
import Header from '@/app/components/header';
import Loader from '@/app/components/loader';
import IsLoadingProvider from '@/app/providers/loadingProvider';
import FavoriteHeroProvider from '@/app/providers/favoriteHeroesProvider';
import '@fortawesome/fontawesome-svg-core/styles.css';
import '@/app/styles/globals.css';
import '@/app/styles/layout.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <FavoriteHeroProvider>
          <Header />
          <IsLoadingProvider>
            <Loader />
            <main>{children}</main>
          </IsLoadingProvider>
        </FavoriteHeroProvider>
      </body>
    </html>
  )
}
